-- Deprecated RLS-only entry point.
--
-- RLS is now managed together with constraints, rate limits, and RPC functions:
--   supabase/migrations/20260214_guestbook_and_counter_hardening.sql
--
-- Keeping the policies in one migration prevents drift between direct table
-- permissions and the frontend's RPC-only write path.
