-- Deprecated setup entry point.
--
-- The active schema, RPC functions, RLS policies, and rate limits live in:
--   supabase/migrations/20260214_guestbook_and_counter_hardening.sql
--
-- Do not use the old visitor_counter/rate_limiting setup. The current frontend
-- expects public.page_views, public.guestbook_messages, public.request_limits,
-- and the increment_page_view / submit_guestbook_message RPC functions.
