title: Xi's Space
description: A personal website and blog of Xi Li, Associate Professor of Logic at Central South University.
baseurl: ""
url: "https://rickylixi.github.io"
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
markdown: kramdown
permalink: pretty
exclude: ["Gemfile", "Gemfile.lock"]