title: Xi's Blog
baseurl: ""
url: "https://rickylixi.github.io"
markdown: kramdown
kramdown:
  math_engine: null
  input: GFM
  syntax_highlighter_opts:
    disable: true
permalink: /:year/:month/:day/:title.html
paginate: 5
