title: Xi's Blog
description: Posts and notes by Xi Li.
baseurl: ""
url: "https://rickylixi.github.io"
timezone: Asia/Shanghai
markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM
  syntax_highlighter_opts:
    disable: true
permalink: /:year/:month/:day/:title.html
paginate: 5
paginate_path: "/page:num/"
